---
# we modify the file later but need the original DNS forwarder
- name: make a copy of original resolv.conf
  tags:
    - ipa
  command: cp /etc/resolv.conf /etc/resolv.conf.orig
  args:
    creates: /etc/resolv.conf.orig

- name: Get default DNS
  tags:
    - ipa
  resolver: resolvconf=/etc/resolv.conf.orig
  register: dns_forwarder
  changed_when: false

- name: Get reverse zone
  tags:
    - ipa
    - setup
  reversezone: ipaddress={{ ansible_default_ipv4.address }}
  register: reversezone
  changed_when: false

- name: Remove chrony (FreeIPA uses ntpd)
  tags:
    - ipa
    - package-install
  package: name=chrony state=absent
  when: package_install

- name: install FreeIPA client package
  tags:
    - ipa
    - package-install
    - network
  package: name={{ item }} state=present
  with_items:
   - ipa-client
   - ipa-admintools
  when: package_install

- name: Copy workaround tmpfiles.d for /var/run/ipa
  tags:
    - ipa
  copy:
    src=ipa-client.tmpfiles.conf
    dest=/etc/tmpfiles.d/ipa-client.conf
    owner=root
    group=root
    mode=0644

- name: Gather IPA facts
  tags:
    - ipa
    - setup
  ipa_facts: domain={{ ipa_domain }}

- name: Set install facts
  tags:
    - ipa
    - setup
  changed_when: false
  set_fact:
    install_ipa_nfsserver: "{{ 'ipa_nfsserver' in groups and groups['ipa_nfsserver'] }}"
    install_ipa_replica: "{{ 'ipaserver_replica' in groups and groups['ipaserver_replica'] }}"
