Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    config.vm.define "vm2" do |vm2|
      vm2.vm.box = "bullseye64"
      v.name = "vm2"
      v.memory = 2048
      v.cpus = 2
    end

    config.vm.define "vm3" do |vm3|
      vm3.vm.box = "bullseye64"
      v.name = "vm3"
      v.memory = 2048
      v.cpus = 2
    end

  end
end