Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "debian/stretch64"
  config.vm.provider 'lxd' do |lxd|
    lxd.nesting = true
    lxd.privileged = true
  end
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "debian/stretch64"
  config.vm.provider 'lxd' do |lxd|
    lxd.nesting = true
    lxd.privileged = true
  end
  end

  config.vm.define "vm3" do |vm3|
    vm3.vm.box = "debian/stretch64"
  config.vm.provider 'lxd' do |lxd|
    lxd.nesting = true
    lxd.privileged = true
  end
  end

end
